
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Apr 24 2026 12:56:48 CEST (Apr 24 2026 10:56:48 UTC)

// Verification Directory fv/cnn_top 

module addr_gen(clk, rst_n, enable, layer_sel, mac_valid, acc_clear,
     act_rd_en, act_zero, \act_rd_addr[0] , \act_rd_addr[1] ,
     \act_rd_addr[2] , \act_rd_addr[3] , w_rd_en, \w_idx[0] , \w_idx[1]
     , \w_idx[2] , \w_idx[3] , out_wr_en, out_wr_addr, layer_done);
  input clk, rst_n, enable, layer_sel;
  output mac_valid, acc_clear, out_wr_en, layer_done;
  output [3:0] act_rd_en, act_zero, w_rd_en;
  output [15:0] \act_rd_addr[0] , \act_rd_addr[1] , \act_rd_addr[2] ,
       \act_rd_addr[3] , out_wr_addr;
  output [8:0] \w_idx[0] , \w_idx[1] , \w_idx[2] , \w_idx[3] ;
  wire clk, rst_n, enable, layer_sel;
  wire mac_valid, acc_clear, out_wr_en, layer_done;
  wire [3:0] act_rd_en, act_zero, w_rd_en;
  wire [15:0] \act_rd_addr[0] , \act_rd_addr[1] , \act_rd_addr[2] ,
       \act_rd_addr[3] , out_wr_addr;
  wire [8:0] \w_idx[0] , \w_idx[1] , \w_idx[2] , \w_idx[3] ;
  wire [2:0] state_r;
  wire [5:0] tap_base;
  wire [2:0] oc;
  wire [4:0] y;
  wire [4:0] x;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, n_0, n_1, n_2, n_3, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_97;
  sg13g2_and3_2 g1690__2398(.A (n_90), .B (state_r[2]), .C
       (state_r[0]), .X (layer_done));
  sg13g2_nand2_1 g1691__5107(.A (n_90), .B (state_r[2]), .Y (n_97));
  sg13g2_dfrbp_1 \tap_base_reg[5] (.RESET_B (rst_n), .CLK (clk), .D
       (n_86), .Q (tap_base[5]), .Q_N (UNCONNECTED));
  sg13g2_dfrbp_1 \tap_base_reg[3] (.RESET_B (rst_n), .CLK (clk), .D
       (n_89), .Q (tap_base[3]), .Q_N (UNCONNECTED0));
  sg13g2_dfrbp_1 \tap_base_reg[4] (.RESET_B (rst_n), .CLK (clk), .D
       (n_87), .Q (tap_base[4]), .Q_N (n_3));
  sg13g2_sdfbbp_1 \tap_base_reg[2] (.RESET_B (rst_n), .SET_B (1'b1),
       .CLK (clk), .D (n_83), .SCD (n_79), .SCE (tap_base[2]), .Q
       (tap_base[2]), .Q_N (UNCONNECTED1));
  sg13g2_inv_1 g2519(.A (n_88), .Y (n_89));
  sg13g2_a22oi_1 g2520__6260(.A1 (n_83), .A2 (n_21), .B1 (tap_base[3]),
       .B2 (n_79), .Y (n_88));
  sg13g2_inv_1 g2521(.A (n_85), .Y (n_87));
  sg13g2_inv_1 g2522(.A (n_84), .Y (n_86));
  sg13g2_a22oi_1 g2523__4319(.A1 (n_83), .A2 (n_30), .B1 (tap_base[4]),
       .B2 (n_79), .Y (n_85));
  sg13g2_a22oi_1 g2524__8428(.A1 (n_83), .A2 (n_36), .B1 (tap_base[5]),
       .B2 (n_79), .Y (n_84));
  sg13g2_dfrbp_1 \oc_reg[1] (.RESET_B (rst_n), .CLK (clk), .D (n_81),
       .Q (oc[1]), .Q_N (UNCONNECTED2));
  sg13g2_dfrbp_1 \oc_reg[2] (.RESET_B (rst_n), .CLK (clk), .D (n_82),
       .Q (oc[2]), .Q_N (UNCONNECTED3));
  sg13g2_sdfbbp_1 \oc_reg[0] (.RESET_B (rst_n), .SET_B (1'b1), .CLK
       (clk), .D (n_74), .SCD (n_62), .SCE (oc[0]), .Q (oc[0]), .Q_N
       (UNCONNECTED4));
  sg13g2_dfrbp_1 \state_r_reg[0] (.RESET_B (rst_n), .CLK (clk), .D
       (n_80), .Q (state_r[0]), .Q_N (UNCONNECTED5));
  sg13g2_a21o_1 g2529__5526(.A1 (n_65), .A2 (oc[2]), .B1 (n_77), .X
       (n_82));
  sg13g2_a21o_1 g2530__6783(.A1 (n_69), .A2 (oc[1]), .B1 (n_78), .X
       (n_81));
  sg13g2_nor2b_1 g2531__3680(.A (n_79), .B_N (n_22), .Y (n_83));
  sg13g2_nand3_1 g2532__1617(.A (n_70), .B (n_16), .C (n_37), .Y
       (n_80));
  sg13g2_dfrbp_1 \state_r_reg[2] (.RESET_B (rst_n), .CLK (clk), .D
       (n_75), .Q (state_r[2]), .Q_N (UNCONNECTED6));
  sg13g2_and2_1 g2534__2802(.A (n_76), .B (oc[0]), .X (n_78));
  sg13g2_nor3_1 g2535__1705(.A (oc[2]), .B (n_11), .C (n_73), .Y
       (n_77));
  sg13g2_and3_2 g2536__5122(.A (n_72), .B (n_37), .C (n_25), .X (n_79));
  sg13g2_dfrbp_1 \y_reg[1] (.RESET_B (rst_n), .CLK (clk), .D (n_71), .Q
       (y[1]), .Q_N (UNCONNECTED7));
  sg13g2_dfrbp_1 \y_reg[2] (.RESET_B (rst_n), .CLK (clk), .D (n_66), .Q
       (y[2]), .Q_N (UNCONNECTED8));
  sg13g2_dfrbp_1 \y_reg[3] (.RESET_B (rst_n), .CLK (clk), .D (n_67), .Q
       (y[3]), .Q_N (UNCONNECTED9));
  sg13g2_nor2_1 g2540__8246(.A (oc[1]), .B (n_73), .Y (n_76));
  sg13g2_nand2_1 g2541__7098(.A (n_64), .B (n_16), .Y (n_75));
  sg13g2_dfrbp_1 \y_reg[4] (.RESET_B (rst_n), .CLK (clk), .D (n_68), .Q
       (y[4]), .Q_N (n_2));
  sg13g2_sdfbbp_1 \y_reg[0] (.RESET_B (rst_n), .SET_B (1'b1), .CLK
       (clk), .D (n_56), .SCD (n_48), .SCE (y[0]), .Q (y[0]), .Q_N
       (UNCONNECTED10));
  sg13g2_inv_1 g2544(.A (n_73), .Y (n_74));
  sg13g2_nand2_1 g2545__6131(.A (n_63), .B (n_22), .Y (n_72));
  sg13g2_a21o_1 g2546__1881(.A1 (n_51), .A2 (y[1]), .B1 (n_58), .X
       (n_71));
  sg13g2_nand2b_1 g2547__5115(.A_N (n_63), .B (n_22), .Y (n_70));
  sg13g2_a21o_1 g2548__7482(.A1 (n_38), .A2 (n_7), .B1 (n_62), .X
       (n_69));
  sg13g2_nand2b_1 g2549__4733(.A_N (n_62), .B (n_38), .Y (n_73));
  sg13g2_a21o_1 g2550__6161(.A1 (n_53), .A2 (y[4]), .B1 (n_61), .X
       (n_68));
  sg13g2_a21o_1 g2551__9315(.A1 (n_50), .A2 (y[3]), .B1 (n_60), .X
       (n_67));
  sg13g2_a21o_1 g2552__9945(.A1 (n_52), .A2 (y[2]), .B1 (n_59), .X
       (n_66));
  sg13g2_a21o_1 g2553__2883(.A1 (n_38), .A2 (n_11), .B1 (n_62), .X
       (n_65));
  sg13g2_a22oi_1 g2554__2346(.A1 (n_54), .A2 (n_33), .B1 (state_r[0]),
       .B2 (n_12), .Y (n_64));
  sg13g2_a21oi_1 g2555__1666(.A1 (n_47), .A2 (n_36), .B1 (n_40), .Y
       (n_63));
  sg13g2_nor2b_1 g2556__7410(.A (n_54), .B_N (n_28), .Y (n_62));
  sg13g2_dfrbp_1 \x_reg[4] (.RESET_B (rst_n), .CLK (clk), .D (n_55), .Q
       (x[4]), .Q_N (UNCONNECTED11));
  sg13g2_nor3_1 g2558__6417(.A (y[4]), .B (n_32), .C (n_57), .Y (n_61));
  sg13g2_nor3_1 g2559__5477(.A (y[3]), .B (n_24), .C (n_57), .Y (n_60));
  sg13g2_nor3_1 g2560__2398(.A (y[2]), .B (n_14), .C (n_57), .Y (n_59));
  sg13g2_nor3_1 g2561__5107(.A (n_6), .B (y[1]), .C (n_57), .Y (n_58));
  sg13g2_inv_1 g2562(.A (n_57), .Y (n_56));
  sg13g2_dfrbp_1 \x_reg[3] (.RESET_B (rst_n), .CLK (clk), .D (n_45), .Q
       (x[3]), .Q_N (UNCONNECTED12));
  sg13g2_dfrbp_1 \x_reg[2] (.RESET_B (rst_n), .CLK (clk), .D (n_46), .Q
       (x[2]), .Q_N (UNCONNECTED13));
  sg13g2_dfrbp_1 \x_reg[1] (.RESET_B (rst_n), .CLK (clk), .D (n_44), .Q
       (x[1]), .Q_N (UNCONNECTED14));
  sg13g2_nand2b_1 g2566__6260(.A_N (n_48), .B (n_8), .Y (n_57));
  sg13g2_sdfbbp_1 \x_reg[0] (.RESET_B (rst_n), .SET_B (1'b1), .CLK
       (clk), .D (n_1), .SCD (n_37), .SCE (x[0]), .Q (x[0]), .Q_N
       (UNCONNECTED15));
  sg13g2_inv_1 g2568(.A (n_49), .Y (n_55));
  sg13g2_a21o_1 g2569__4319(.A1 (n_32), .A2 (n_9), .B1 (n_48), .X
       (n_53));
  sg13g2_a21o_1 g2570__8428(.A1 (n_9), .A2 (n_14), .B1 (n_48), .X
       (n_52));
  sg13g2_a21o_1 g2571__5526(.A1 (n_1), .A2 (n_6), .B1 (n_48), .X
       (n_51));
  sg13g2_a21o_1 g2572__6783(.A1 (n_9), .A2 (n_24), .B1 (n_48), .X
       (n_50));
  sg13g2_a22oi_1 g2573__3680(.A1 (n_0), .A2 (n_9), .B1 (x[4]), .B2
       (n_37), .Y (n_49));
  sg13g2_nor3_1 g2574__1617(.A (n_2), .B (n_32), .C (n_39), .Y (n_54));
  sg13g2_nand3_1 g2575__2802(.A (n_35), .B (layer_sel), .C
       (tap_base[2]), .Y (n_47));
  sg13g2_and2_1 g2576__1705(.A (n_39), .B (n_28), .X (n_48));
  sg13g2_inv_1 g2577(.A (n_43), .Y (n_46));
  sg13g2_inv_1 g2578(.A (n_42), .Y (n_45));
  sg13g2_inv_1 g2579(.A (n_41), .Y (n_44));
  sg13g2_a22oi_1 g2580__5122(.A1 (n_9), .A2 (n_26), .B1 (x[2]), .B2
       (n_37), .Y (n_43));
  sg13g2_a22oi_1 g2581__8246(.A1 (n_34), .A2 (n_9), .B1 (x[3]), .B2
       (n_37), .Y (n_42));
  sg13g2_a22oi_1 g2582__7098(.A1 (n_37), .A2 (x[1]), .B1 (n_18), .B2
       (n_9), .Y (n_41));
  sg13g2_a21oi_1 g2583__6131(.A1 (n_29), .A2 (n_13), .B1 (layer_sel),
       .Y (n_40));
  sg13g2_nand3_1 g2585__1881(.A (n_31), .B (n_8), .C (x[4]), .Y (n_39));
  sg13g2_dfrbp_1 \state_r_reg[1] (.RESET_B (rst_n), .CLK (clk), .D
       (n_27), .Q (state_r[1]), .Q_N (n_90));
  sg13g2_nor2b_1 g2587__5115(.A (n_33), .B_N (n_8), .Y (n_38));
  sg13g2_nor2b_1 g2588__7482(.A (n_8), .B_N (n_28), .Y (n_37));
  sg13g2_nor2_1 g2589__4733(.A (n_21), .B (n_30), .Y (n_35));
  sg13g2_xnor2_1 g2590__6161(.A (x[3]), .B (n_23), .Y (n_34));
  sg13g2_xor2_1 g2591__9315(.A (tap_base[5]), .B (n_20), .X (n_36));
  sg13g2_nor2_1 g2593__9945(.A (n_11), .B (n_19), .Y (n_33));
  sg13g2_nand2b_1 g2594__2883(.A_N (n_24), .B (y[3]), .Y (n_32));
  sg13g2_nor2b_1 g2595__2346(.A (n_23), .B_N (x[3]), .Y (n_31));
  sg13g2_inv_1 g2596(.A (n_30), .Y (n_29));
  sg13g2_nand2b_1 g2597__1666(.A_N (n_22), .B (n_25), .Y (n_27));
  sg13g2_xnor2_1 g2598__7410(.A (x[2]), .B (n_10), .Y (n_26));
  sg13g2_a21oi_1 g2599__6417(.A1 (n_17), .A2 (n_3), .B1 (n_20), .Y
       (n_30));
  sg13g2_nand3b_1 g2600__5477(.A_N (state_r[0]), .B (n_15), .C
       (enable), .Y (n_28));
  sg13g2_nand2_1 g2601__2398(.A (n_15), .B (state_r[0]), .Y (n_25));
  sg13g2_nand2b_1 g2602__5107(.A_N (n_14), .B (y[2]), .Y (n_24));
  sg13g2_nand2b_1 g2603__6260(.A_N (n_10), .B (x[2]), .Y (n_23));
  sg13g2_nor2b_1 g2604__4319(.A (state_r[0]), .B_N (n_12), .Y (n_22));
  sg13g2_xor2_1 g2605__8428(.A (oc[2]), .B (layer_sel), .X (n_19));
  sg13g2_xor2_1 g2606__5526(.A (x[1]), .B (x[0]), .X (n_18));
  sg13g2_o21ai_1 g2607__6783(.A1 (n_5), .A2 (tap_base[3]), .B1 (n_13),
       .Y (n_21));
  sg13g2_nor2_1 g2608__3680(.A (n_3), .B (n_17), .Y (n_20));
  sg13g2_nand2_1 g2609__1617(.A (tap_base[2]), .B (tap_base[3]), .Y
       (n_17));
  sg13g2_nand2_1 g2610__2802(.A (layer_done), .B (enable), .Y (n_16));
  sg13g2_nor2_1 g2611__1705(.A (state_r[2]), .B (state_r[1]), .Y
       (n_15));
  sg13g2_nand2_1 g2612__5122(.A (y[0]), .B (y[1]), .Y (n_14));
  sg13g2_buf_1 g2613(.A (n_8), .X (n_9));
  sg13g2_nand2_1 g2614__8246(.A (tap_base[3]), .B (n_5), .Y (n_13));
  sg13g2_nor2b_1 g2615__7098(.A (state_r[2]), .B_N (state_r[1]), .Y
       (n_12));
  sg13g2_nand2_1 g2616__6131(.A (oc[0]), .B (oc[1]), .Y (n_11));
  sg13g2_nand2_1 g2617__1881(.A (x[0]), .B (x[1]), .Y (n_10));
  sg13g2_nor2_1 g2618__5115(.A (state_r[0]), .B (n_97), .Y (n_8));
  sg13g2_inv_1 g2622(.A (oc[0]), .Y (n_7));
  sg13g2_inv_1 g2624(.A (y[0]), .Y (n_6));
  sg13g2_inv_1 g2630(.A (tap_base[2]), .Y (n_5));
  sg13g2_buf_1 drc_bufs2634(.A (n_9), .X (n_1));
  sg13g2_xor2_1 g2__7482(.A (x[4]), .B (n_31), .X (n_0));
endmodule

module controller_fsm(clk, rst_n, start, conv_done, pool_done,
     conv_start, pool_start, layer_sel, mode_sel, src_sel, dst_sel,
     done);
  input clk, rst_n, start, conv_done, pool_done;
  output conv_start, pool_start, layer_sel, mode_sel, src_sel, dst_sel,
       done;
  wire clk, rst_n, start, conv_done, pool_done;
  wire conv_start, pool_start, layer_sel, mode_sel, src_sel, dst_sel,
       done;
  wire [2:0] state_r;
  wire UNCONNECTED16, UNCONNECTED17, UNCONNECTED18, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_15, n_16, n_17, n_18, n_19, n_20;
  sg13g2_inv_1 g393(.A (n_20), .Y (layer_sel));
  sg13g2_nand2b_1 g446__4733(.A_N (n_17), .B (conv_done), .Y (n_15));
  sg13g2_or2_1 g447__6161(.A (state_r[1]), .B (n_19), .X (n_17));
  sg13g2_nand2b_1 g448__9315(.A_N (n_20), .B (conv_done), .Y (n_16));
  sg13g2_nand3b_1 g449__9945(.A_N (state_r[0]), .B (start), .C (n_12),
       .Y (n_18));
  sg13g2_or2_1 g450__2883(.A (done), .B (n_12), .X (n_20));
  sg13g2_nand2b_1 g451__2346(.A_N (done), .B (state_r[0]), .Y (n_19));
  sg13g2_dfrbp_1 \state_r_reg[0] (.RESET_B (rst_n), .CLK (clk), .D
       (n_11), .Q (state_r[0]), .Q_N (UNCONNECTED16));
  sg13g2_dfrbp_1 done_reg(.RESET_B (rst_n), .CLK (clk), .D (n_10), .Q
       (done), .Q_N (n_2));
  sg13g2_nand3_1 g477__1666(.A (n_18), .B (n_6), .C (n_9), .Y (n_11));
  sg13g2_dfrbp_1 \state_r_reg[1] (.RESET_B (rst_n), .CLK (clk), .D
       (n_8), .Q (state_r[1]), .Q_N (n_12));
  sg13g2_o21ai_1 g479__7410(.A1 (n_20), .A2 (n_4), .B1 (n_7), .Y
       (n_10));
  sg13g2_nand2b_1 g480__6417(.A_N (conv_done), .B (n_5), .Y (n_9));
  sg13g2_o21ai_1 g481__5477(.A1 (n_20), .A2 (n_3), .B1 (n_15), .Y
       (n_8));
  sg13g2_or4_1 g482__2398(.A (n_2), .B (state_r[1]), .C (state_r[0]),
       .D (start), .X (n_7));
  sg13g2_nand2b_1 g483__5107(.A_N (n_16), .B (n_4), .Y (n_6));
  sg13g2_o21ai_1 g484__6260(.A1 (n_19), .A2 (pool_done), .B1 (n_17), .Y
       (n_5));
  sg13g2_inv_1 g485(.A (n_4), .Y (n_3));
  sg13g2_nand2_1 g486__4319(.A (pool_done), .B (state_r[0]), .Y (n_4));
  sg13g2_dfrbp_1 conv_start_reg(.RESET_B (rst_n), .CLK (clk), .D (n_1),
       .Q (conv_start), .Q_N (UNCONNECTED17));
  sg13g2_dfrbp_1 pool_start_reg(.RESET_B (rst_n), .CLK (clk), .D (n_0),
       .Q (pool_start), .Q_N (UNCONNECTED18));
  sg13g2_nand2_1 g399__8428(.A (n_18), .B (n_15), .Y (n_1));
  sg13g2_nor2_1 g400__5526(.A (state_r[0]), .B (n_16), .Y (n_0));
endmodule

module pool_engine(clk, rst_n, pool_start, pool_done, sram_rd_addr,
     sram_rd_data, sram_wr_addr, sram_wr_data, sram_wr_en);
  input clk, rst_n, pool_start;
  input [7:0] sram_rd_data;
  output pool_done, sram_wr_en;
  output [12:0] sram_rd_addr, sram_wr_addr;
  output [7:0] sram_wr_data;
  wire clk, rst_n, pool_start;
  wire [7:0] sram_rd_data;
  wire pool_done, sram_wr_en;
  wire [12:0] sram_rd_addr, sram_wr_addr;
  wire [7:0] sram_wr_data;
  wire [2:0] state_reg;
  wire [2:0] ch;
  wire [2:0] out_row;
  wire [2:0] out_col;
  wire UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22,
       UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26;
  wire UNCONNECTED27, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_43, n_44, n_45, n_46, n_47;
  wire n_49, n_52, n_53, n_54, n_55, n_57, n_58, n_59;
  wire n_61, n_74, n_75, n_76, n_77;
  sg13g2_and3_1 g795__6783(.A (state_reg[1]), .B (state_reg[0]), .C
       (state_reg[2]), .X (pool_done));
  sg13g2_nand2_1 g796__3680(.A (state_reg[0]), .B (state_reg[1]), .Y
       (n_61));
  sg13g2_dfrbp_1 \state_reg_reg[2] (.RESET_B (rst_n), .CLK (clk), .D
       (n_0), .Q (state_reg[2]), .Q_N (n_2));
  sg13g2_dfrbp_1 \ch_reg[1] (.RESET_B (rst_n), .CLK (clk), .D (n_58),
       .Q (ch[1]), .Q_N (UNCONNECTED19));
  sg13g2_dfrbp_1 \ch_reg[0] (.RESET_B (rst_n), .CLK (clk), .D (n_57),
       .Q (ch[0]), .Q_N (UNCONNECTED20));
  sg13g2_dfrbp_1 \ch_reg[2] (.RESET_B (rst_n), .CLK (clk), .D (n_75),
       .Q (ch[2]), .Q_N (UNCONNECTED21));
  sg13g2_nor2_1 g1272__1617(.A (n_20), .B (n_53), .Y (n_58));
  sg13g2_dfrbp_1 \out_row_reg[2] (.RESET_B (rst_n), .CLK (clk), .D
       (n_54), .Q (out_row[2]), .Q_N (n_1));
  sg13g2_nor2_1 g1274__2802(.A (n_20), .B (n_52), .Y (n_57));
  sg13g2_nand4_1 g1276__5122(.A (n_41), .B (out_row[0]), .C
       (out_row[1]), .D (out_col[2]), .Y (n_55));
  sg13g2_dfrbp_1 \out_row_reg[1] (.RESET_B (rst_n), .CLK (clk), .D
       (n_49), .Q (out_row[1]), .Q_N (UNCONNECTED22));
  sg13g2_dfrbp_1 \state_reg_reg[1] (.RESET_B (rst_n), .CLK (clk), .D
       (n_77), .Q (state_reg[1]), .Q_N (UNCONNECTED23));
  sg13g2_a21o_1 g1279__8246(.A1 (n_43), .A2 (out_row[2]), .B1 (n_44),
       .X (n_54));
  sg13g2_a22oi_1 g1280__7098(.A1 (n_46), .A2 (n_11), .B1 (ch[1]), .B2
       (n_45), .Y (n_53));
  sg13g2_xor2_1 g1281__6131(.A (ch[0]), .B (n_45), .X (n_52));
  sg13g2_dfrbp_1 \out_row_reg[0] (.RESET_B (rst_n), .CLK (clk), .D
       (n_47), .Q (out_row[0]), .Q_N (UNCONNECTED24));
  sg13g2_a21o_1 g1285__5115(.A1 (n_37), .A2 (out_row[1]), .B1 (n_38),
       .X (n_49));
  sg13g2_a21o_1 g1287__4733(.A1 (n_33), .A2 (out_row[0]), .B1 (n_32),
       .X (n_47));
  sg13g2_dfrbp_1 \out_col_reg[2] (.RESET_B (rst_n), .CLK (clk), .D
       (n_39), .Q (out_col[2]), .Q_N (UNCONNECTED25));
  sg13g2_dfrbp_1 \out_col_reg[1] (.RESET_B (rst_n), .CLK (clk), .D
       (n_40), .Q (out_col[1]), .Q_N (UNCONNECTED26));
  sg13g2_inv_1 g1290(.A (n_45), .Y (n_46));
  sg13g2_nor3_1 g1291__6161(.A (out_row[2]), .B (n_8), .C (n_35), .Y
       (n_44));
  sg13g2_o21ai_1 g1292__9315(.A1 (n_2), .A2 (n_36), .B1 (n_21), .Y
       (n_43));
  sg13g2_nand4_1 g1294__2883(.A (n_36), .B (n_18), .C (n_7), .D
       (out_row[2]), .Y (n_45));
  sg13g2_and3_1 g1295__2346(.A (n_27), .B (out_col[0]), .C
       (out_col[1]), .X (n_41));
  sg13g2_a21o_1 g1296__1666(.A1 (n_28), .A2 (out_col[1]), .B1 (n_19),
       .X (n_40));
  sg13g2_dfrbp_1 \out_col_reg[0] (.RESET_B (rst_n), .CLK (clk), .D
       (n_34), .Q (out_col[0]), .Q_N (UNCONNECTED27));
  sg13g2_a21o_1 g1298__7410(.A1 (n_24), .A2 (out_col[2]), .B1 (n_26),
       .X (n_39));
  sg13g2_nor3_1 g1299__6417(.A (out_row[1]), .B (n_8), .C (n_30), .Y
       (n_38));
  sg13g2_o21ai_1 g1300__5477(.A1 (n_2), .A2 (n_31), .B1 (n_21), .Y
       (n_37));
  sg13g2_inv_1 g1301(.A (n_36), .Y (n_35));
  sg13g2_and2_1 g1302__2398(.A (n_31), .B (out_row[1]), .X (n_36));
  sg13g2_dfrbp_1 \state_reg_reg[0] (.RESET_B (rst_n), .CLK (clk), .D
       (n_25), .Q (state_reg[0]), .Q_N (n_59));
  sg13g2_nand3_1 g1304__5107(.A (n_29), .B (n_13), .C (n_15), .Y
       (n_34));
  sg13g2_o21ai_1 g1305__6260(.A1 (n_2), .A2 (n_23), .B1 (n_21), .Y
       (n_33));
  sg13g2_nor3_1 g1306__4319(.A (out_row[0]), .B (n_8), .C (n_22), .Y
       (n_32));
  sg13g2_inv_1 g1307(.A (n_31), .Y (n_30));
  sg13g2_o21ai_1 g1308__8428(.A1 (n_10), .A2 (n_14), .B1 (out_col[0]),
       .Y (n_29));
  sg13g2_o21ai_1 g1309__5526(.A1 (n_2), .A2 (n_4), .B1 (n_21), .Y
       (n_28));
  sg13g2_and2_1 g1310__6783(.A (n_23), .B (out_row[0]), .X (n_31));
  sg13g2_nor3_1 g1311__3680(.A (out_col[2]), .B (n_8), .C (n_16), .Y
       (n_26));
  sg13g2_nand3_1 g1312__1617(.A (n_12), .B (n_5), .C (n_8), .Y (n_25));
  sg13g2_o21ai_1 g1313__2802(.A1 (n_2), .A2 (n_17), .B1 (n_21), .Y
       (n_24));
  sg13g2_nor3_1 g1314__1705(.A (n_2), .B (n_1), .C (n_18), .Y (n_27));
  sg13g2_inv_1 g1315(.A (n_23), .Y (n_22));
  sg13g2_and2_1 g1316__5122(.A (n_17), .B (out_col[2]), .X (n_23));
  sg13g2_nor2_1 g1317__8246(.A (n_9), .B (n_14), .Y (n_21));
  sg13g2_nor3_1 g1318__7098(.A (out_col[1]), .B (n_3), .C (n_8), .Y
       (n_19));
  sg13g2_nor3_1 g1319__6131(.A (state_reg[1]), .B (state_reg[2]), .C
       (n_5), .Y (n_20));
  sg13g2_inv_1 g1320(.A (n_17), .Y (n_16));
  sg13g2_nand2_1 g1321__1881(.A (n_4), .B (n_2), .Y (n_15));
  sg13g2_nand2_1 g1322__5115(.A (n_6), .B (ch[2]), .Y (n_18));
  sg13g2_and2_1 g1323__7482(.A (n_4), .B (out_col[1]), .X (n_17));
  sg13g2_nand3b_1 g1324__4733(.A_N (out_col[0]), .B (n_7), .C
       (state_reg[1]), .Y (n_13));
  sg13g2_o21ai_1 g1325__6161(.A1 (n_59), .A2 (state_reg[2]), .B1
       (state_reg[1]), .Y (n_12));
  sg13g2_xor2_1 g1326__9315(.A (ch[1]), .B (ch[0]), .X (n_11));
  sg13g2_o21ai_1 g1327__9945(.A1 (state_reg[2]), .A2 (pool_start), .B1
       (n_59), .Y (n_14));
  sg13g2_inv_1 g1329(.A (n_8), .Y (n_7));
  sg13g2_nor2_1 g1330__2883(.A (state_reg[1]), .B (n_2), .Y (n_10));
  sg13g2_nor2b_1 g1331__2346(.A (state_reg[2]), .B_N (state_reg[1]), .Y
       (n_9));
  sg13g2_nand2_1 g1332__1666(.A (state_reg[2]), .B (n_59), .Y (n_8));
  sg13g2_inv_1 g1333(.A (n_4), .Y (n_3));
  sg13g2_and2_1 g1334__7410(.A (ch[1]), .B (ch[0]), .X (n_6));
  sg13g2_nand2_1 g1335__6417(.A (pool_start), .B (n_59), .Y (n_5));
  sg13g2_and2_1 g1336__5477(.A (state_reg[1]), .B (out_col[0]), .X
       (n_4));
  sg13g2_nand3b_1 g2__2398(.A_N (n_10), .B (n_55), .C (n_61), .Y (n_0));
  sg13g2_nor2_1 g2(.A (n_74), .B (n_20), .Y (n_75));
  sg13g2_a21oi_1 g3(.A1 (n_6), .A2 (n_46), .B1 (ch[2]), .Y (n_74));
  sg13g2_a21o_1 g1359(.A1 (n_36), .A2 (n_27), .B1 (n_76), .X (n_77));
  sg13g2_xnor2_1 g1360(.A (n_59), .B (n_9), .Y (n_76));
endmodule

module cnn_top(clk, rst_n, start, done);
  input clk, rst_n, start;
  output done;
  wire clk, rst_n, start;
  wire done;
  wire [12:0] lane0_rd_addr;
  wire [15:0] \act_rd_addr[1] ;
  wire [15:0] \act_rd_addr[2] ;
  wire [15:0] \act_rd_addr[3] ;
  wire [3:0] w_rd_en;
  wire [8:0] \w_idx[0] ;
  wire [8:0] \w_idx[1] ;
  wire [8:0] \w_idx[2] ;
  wire [8:0] \w_idx[3] ;
  wire [15:0] out_wr_addr;
  wire [12:0] pool_rd_addr;
  wire [12:0] pool_wr_addr;
  wire [7:0] pool_wr_data;
  wire UNCONNECTED28, UNCONNECTED29, UNCONNECTED30, UNCONNECTED31,
       UNCONNECTED32, UNCONNECTED33, UNCONNECTED34, UNCONNECTED35;
  wire UNCONNECTED36, UNCONNECTED37, UNCONNECTED38, UNCONNECTED39,
       UNCONNECTED40, UNCONNECTED41, UNCONNECTED_HIER_Z,
       UNCONNECTED_HIER_Z0;
  wire UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6,
       acc_clear, \act_rd_addr[0][0] ;
  wire ag_enable, conv_start, conv_start_d1, dst_sel, layer_done,
       layer_done_d1, layer_sel, mac_valid;
  wire mode_sel, n_0, n_1, n_3, out_wr_en, pool_done, pool_start,
       pool_wr_en;
  wire src_sel;
  addr_gen u_ag(.clk (clk), .rst_n (rst_n), .enable (ag_enable),
       .layer_sel (layer_sel), .mac_valid (mac_valid), .acc_clear
       (acc_clear), .act_rd_en ({UNCONNECTED31, UNCONNECTED30,
       UNCONNECTED29, UNCONNECTED28}), .act_zero ({UNCONNECTED35,
       UNCONNECTED34, UNCONNECTED33, UNCONNECTED32}), .\act_rd_addr[0] 
       ({UNCONNECTED38, UNCONNECTED37, UNCONNECTED36,
       lane0_rd_addr[12:1], \act_rd_addr[0][0] }), .\act_rd_addr[1] 
       (\act_rd_addr[1] ), .\act_rd_addr[2]  (\act_rd_addr[2] ),
       .\act_rd_addr[3]  (\act_rd_addr[3] ), .w_rd_en (w_rd_en),
       .\w_idx[0]  (\w_idx[0] ), .\w_idx[1]  (\w_idx[1] ), .\w_idx[2] 
       (\w_idx[2] ), .\w_idx[3]  (\w_idx[3] ), .out_wr_en (out_wr_en),
       .out_wr_addr (out_wr_addr), .layer_done (layer_done));
  controller_fsm u_ctrl(.clk (clk), .rst_n (rst_n), .start (start),
       .conv_done (n_1), .pool_done (pool_done), .conv_start
       (conv_start), .pool_start (pool_start), .layer_sel (layer_sel),
       .mode_sel (mode_sel), .src_sel (src_sel), .dst_sel (dst_sel),
       .done (done));
  pool_engine u_pool(.clk (clk), .rst_n (rst_n), .pool_start
       (pool_start), .pool_done (pool_done), .sram_rd_addr
       (pool_rd_addr), .sram_rd_data ({UNCONNECTED_HIER_Z6,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z}), .sram_wr_addr (pool_wr_addr),
       .sram_wr_data (pool_wr_data), .sram_wr_en (pool_wr_en));
  sg13g2_inv_1 g78(.A (n_3), .Y (n_1));
  sg13g2_nand2_1 g79__5107(.A (layer_done), .B (layer_done_d1), .Y
       (n_3));
  sg13g2_dfrbp_1 layer_done_d1_reg(.RESET_B (rst_n), .CLK (clk), .D
       (layer_done), .Q (UNCONNECTED39), .Q_N (layer_done_d1));
  sg13g2_dfrbp_1 conv_start_d1_reg(.RESET_B (rst_n), .CLK (clk), .D
       (conv_start), .Q (conv_start_d1), .Q_N (UNCONNECTED40));
  sg13g2_sdfbbp_1 ag_enable_reg(.RESET_B (rst_n), .SET_B (1'b1), .CLK
       (clk), .D (ag_enable), .SCD (n_3), .SCE (n_0), .Q (ag_enable),
       .Q_N (UNCONNECTED41));
  sg13g2_nand2b_1 g81__6260(.A_N (conv_start_d1), .B (n_3), .Y (n_0));
endmodule

